import '../styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import localFont from 'next/font/local';

import HeaderLayout from './headerLayout';
import StyledComponentsRegistry from '@/lib/registry';
const inter = Inter({ subsets: ['latin'] });

const myFont = localFont({
  src: '../../public/assets/fonts/Pretendard-Regular.woff2',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={myFont.className}>
        <StyledComponentsRegistry>
          <HeaderLayout>{children}</HeaderLayout>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
